export const fixtureId = value =>
  `11111111-1111-1111-1111-${String(value).padStart(12, '0')}`;
export const dispatchId = fixtureId(1);
export const userId = fixtureId(2);
export const success = response => ({ success: true, response, errors: [] });

export function workspaceFixture() {
  const stops = [
    ['Pickup', 'Niagara Bottling', 'Mooresville', 'NC'],
    ['Drop', 'Transfer yard', 'Max Meadows', 'VA'],
    ['Hook', 'Transfer yard', 'Max Meadows', 'VA'],
    ['Delivery', 'Keystone Distribution', 'Allentown', 'PA'],
    ['Delivery', 'Harbor Distribution', 'Newark', 'NJ'],
    ['Delivery', 'Capital Distribution', 'Albany', 'NY'],
  ].map(([job, name, city, province], index) => ({
    id: fixtureId(index + 10),
    executionLegId: fixtureId(index < 2 ? 40 : 41),
    sequence: index + 1,
    segmentKey: index < 3 ? `locked-${index}` : 'remaining-leg',
    canEdit: index >= 3,
    canMove: index >= 3,
    canRemove: index >= 3,
    lockReason: index < 3 ? 'Recorded event or transfer boundary.' : null,
    isNew: false,
    job,
    name,
    address:
      index === 1 || index === 2
        ? '145 Major Grahams Road'
        : `${100 + index} Distribution Road`,
    city,
    province,
    country: 'US',
    zipCode: '12345',
    latitude: 40 + index / 10,
    longitude: -75 - index / 10,
    stopNo: index >= 3 ? `DEL-${(index - 2) * 100}` : `PU-${index + 1}`,
    appointmentReference: `APPT-${index + 1}`,
    contactName: 'Receiving office',
    contactPhone: '+1 555 010 0000',
    contactEmail: 'receiving@example.invalid',
    notes: 'Call receiving before arrival. Keep the seal until instructed.',
    commodity: 'Bottled water',
    weight: 12000,
    weightUnit: 'lb',
    pieces: 180,
    pallets: 8,
    temperature: '',
    temperatureUnit: '',
    appointmentMode: index >= 3 ? 'window' : 'at',
    timeZoneId: 'America/New_York',
    scheduledDate: '2026-09-15',
    scheduledTime: '09:00:00',
    scheduledDate2: index >= 3 ? '2026-09-16' : null,
    scheduledTime2: index >= 3 ? '20:00:00' : null,
    truckNumber: index < 2 ? '11005' : '54777',
    trailerNumber: '9P1175',
    driverName: index < 2 ? 'Fixture James' : 'Fixture Iurii',
    coDriverName: '',
    transfer:
      index === 1 || index === 2
        ? {
            switchId: fixtureId(80),
            kind: 'drop_hook',
            action: index === 1 ? 'drop' : 'hook',
            status: 'confirmed',
            actualAt: null,
            outgoingTruckNumber: '11005',
            incomingTruckNumber: '54777',
            outgoingTrailerNumber: '9P1175',
            incomingTrailerNumber: '9P1175',
            outgoingDriverName: 'Fixture James',
            incomingDriverName: 'Fixture Iurii',
          }
        : null,
  }));
  return {
    load: {
      id: dispatchId,
      truckId: fixtureId(3),
      loadNumber: 2048,
      orderNumber: '566552153',
      status: 'in_transit',
      customerName: 'Fixture Broker',
      driverName: 'Fixture Iurii',
      truckNumber: '54777',
      trailerNumber: '9P1175',
      loadedMiles: 1200,
      emptyMiles: 120,
      totalMiles: 1320,
      loadedRatePerMile: 2.5,
      totalRatePerMile: 2.27,
      price: 3000,
      currency: 'USD',
      stops: stops.map((stop, index) => ({
        ...stop,
        isWindow: stop.appointmentMode === 'window',
        appointmentTimeZoneId: stop.timeZoneId,
        executionCompleted: index < 3,
      })),
      eta: {
        calculatedAt: new Date().toISOString(),
        validUntil: new Date(Date.now() + 3_600_000).toISOString(),
        unavailableReason: null,
        assumptions: [],
        stops: stops.slice(3).map((stop, index) => ({
          dispatchId,
          stopId: stop.id,
          arrival: `2026-09-15T${12 + index}:00:00-04:00`,
          timeZoneId: 'America/New_York',
          appointment: '2026-09-15T09:00:00-04:00',
          lateMinutes: 0,
          drivingMinutes: 120 + index * 60,
          restMinutes: 0,
          hours: {
            cycleAtArrivalMinutes: 600 - index * 60,
            cycleAfterStopMinutes: 540 - index * 60,
            cycleVerified: true,
            alternatives: [],
            unavailableReason: null,
          },
        })),
      },
    },
    revision: 1,
    sourceFingerprint: 'synthetic-source-v1',
    sourceName: 'TorqueAI',
    sourceUpdatedAt: '2026-09-14T15:00:00Z',
    metadata: {
      orderNumber: '566552153',
      customerName: 'Fixture Broker',
      price: 3000,
      currency: 'USD',
      brokerCompany: 'Fixture Broker Logistics',
      brokerContact: 'Alex Fixture',
      brokerPhone: '+1 555 010 1000',
      brokerEmail: 'alex@example.invalid',
      brokerReference: 'BR-2048',
      billTo: 'Fixture Broker Accounting',
      loadInstructions: 'Keep the trailer sealed between deliveries.',
    },
    stops,
    canEdit: true,
    readOnlyReason: null,
    locallyManaged: true,
    sourceReviewReason: null,
    history: [],
  };
}

export function activityFixture() {
  const items = [
    {
      id: fixtureId(70),
      dispatchId,
      createdRevision: 1,
      revision: 1,
      kind: 'called-driver',
      text: 'On route. Everything is OK.',
      stopId: null,
      stopLabel: null,
      driverId: null,
      driverName: null,
      actorId: userId,
      actorName: 'Fixture Dispatcher',
      recordedAt: '2026-09-14T14:10:00Z',
      needsAttention: false,
      resolvedBy: null,
      resolvedByName: null,
      resolvedAt: null,
    },
  ];
  const issue = {
    ...items[0],
    id: fixtureId(72),
    createdRevision: 2,
    revision: 2,
    text: 'Previously reported delivery reference issue.',
    needsAttention: true,
  };
  return {
    dispatchId,
    revision: 2,
    items: [issue, ...items],
    nextBeforeRevision: null,
    openCount: 1,
    openItems: [issue],
    nextOpenBeforeRevision: null,
  };
}
