using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

internal static class CommentWrapping
{
  public static async Task RunAsync(string root)
  {
    var updated = 0;
    foreach (
      var folder in new[]
      {
        "Client",
        "Server",
        "Client.Tests",
        "Server.Tests",
        "tools",
      }
    )
    foreach (var file in Sources(Path.Combine(root, folder)))
    {
      var original = await File.ReadAllTextAsync(file);
      if (original.Contains("<auto-generated"))
        continue;
      var text = SourceText.From(original);
      var syntax = await CSharpSyntaxTree.ParseText(text).GetRootAsync();
      var edits = new List<TextChange>();
      foreach (var trivia in syntax.DescendantTrivia())
      {
        if (trivia.RawKind != (int)SyntaxKind.SingleLineCommentTrivia)
          continue;
        var line = text.Lines.GetLineFromPosition(trivia.SpanStart);
        if (line.Span.Length <= 80)
          continue;
        var indent = text.ToString(
          TextSpan.FromBounds(line.Start, trivia.SpanStart)
        );
        if (indent.Any(character => !char.IsWhiteSpace(character)))
          continue;
        var words = trivia
          .ToString()[2..]
          .Split((char[]?)null, StringSplitOptions.RemoveEmptyEntries);
        var lines = new List<string>();
        var current = "//";
        foreach (var word in words)
        {
          if (
            current.Length > 2
            && indent.Length + current.Length + word.Length + 1 > 80
          )
          {
            lines.Add(current);
            current = "//";
          }
          current += " " + word;
        }
        lines.Add(current);
        edits.Add(
          new TextChange(trivia.Span, string.Join("\n" + indent, lines))
        );
      }
      if (edits.Count == 0)
        continue;
      await File.WriteAllTextAsync(file, text.WithChanges(edits).ToString());
      updated++;
    }
    Console.WriteLine($"Wrapped comments in {updated} files.");
  }

  private static IEnumerable<string> Sources(string directory)
  {
    foreach (var file in Directory.EnumerateFiles(directory, "*.cs"))
      if (!file.EndsWith(".Designer.cs"))
        yield return file;
    foreach (var child in new DirectoryInfo(directory).EnumerateDirectories())
    {
      if (
        child.Name is "bin" or "obj" or "node_modules"
        || child.Attributes.HasFlag(FileAttributes.ReparsePoint)
      )
        continue;
      foreach (var file in Sources(child.FullName))
        yield return file;
    }
  }
}
