using Microsoft.Build.Locator;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Editing;
using Microsoft.CodeAnalysis.Formatting;
using Microsoft.CodeAnalysis.MSBuild;
using Microsoft.CodeAnalysis.Simplification;

var commentsOnly = args is ["--comments", _];
if (args.Length != 1 && !commentsOnly)
  throw new ArgumentException("Supply the repository directory.");

var rootDirectory = Path.GetFullPath(args[commentsOnly ? 1 : 0]);
if (commentsOnly)
{
  await CommentWrapping.RunAsync(rootDirectory);
  return;
}
MSBuildLocator.RegisterDefaults();
using var workspace = MSBuildWorkspace.Create();
using var diagnostics = workspace.RegisterWorkspaceFailedHandler(e =>
  Console.Error.WriteLine(e.Diagnostic.Message)
);
var solution = await workspace.OpenSolutionAsync(
  Path.Combine(rootDirectory, "pulsartms.slnx")
);
foreach (
  var path in Directory.EnumerateFiles(
    Path.Combine(rootDirectory, "tools"),
    "*.csproj",
    SearchOption.AllDirectories
  )
)
{
  if (path.Contains("/bin/") || path.Contains("/obj/"))
    continue;
  await workspace.OpenProjectAsync(path);
}
solution = workspace.CurrentSolution;
var baseline = new Dictionary<ProjectId, Dictionary<string, int>>();
foreach (var project in solution.Projects)
{
  var compilation = await project.GetCompilationAsync();
  baseline[project.Id] = ErrorCounts(compilation);
  if (baseline[project.Id].Count > 0)
  {
    Console.WriteLine(
      $"Existing compiler errors in {project.Name}: "
        + baseline[project.Id].Values.Sum()
    );
    foreach (var error in baseline[project.Id].Keys)
      Console.Error.WriteLine(error);
    if (project.Name != "LoadProbe")
      throw new InvalidOperationException(
        "Resolve compiler errors before simplifying source."
      );
  }
}
var pending = new List<(string Path, string Text)>();
foreach (var id in solution.ProjectIds)
{
  var project = solution.GetProject(id)!;
  Console.WriteLine($"Checking {project.Name}");
  foreach (var documentId in project.DocumentIds)
  {
    var document = solution.GetDocument(documentId)!;
    var path = document.FilePath;
    if (
      path is null
      || !path.StartsWith(rootDirectory + Path.DirectorySeparatorChar)
      || path.Contains("/obj/")
      || path.Contains("/bin/")
      || path.EndsWith(".Designer.cs")
    )
      continue;
    var original = await document.GetTextAsync();
    if (original.ToString().Contains("<auto-generated"))
      continue;
    var syntax = await document.GetSyntaxRootAsync();
    var model = await document.GetSemanticModelAsync();
    if (syntax is null || model is null)
      continue;
    var aliases = new Dictionary<string, string>
    {
      ["Domain.Entities.Dispatch.Dispatch"] = "DispatchEntity",
      ["Application.DependencyInjection"] = "ApplicationServices",
      ["Infrastructure.DependencyInjection"] = "InfrastructureServices",
    };
    var aliasNames = syntax
      .DescendantNodes()
      .OfType<QualifiedNameSyntax>()
      .Where(node =>
        !node.Ancestors().Any(parent => parent is UsingDirectiveSyntax)
      )
      .Select(node =>
        (
          Node: node,
          Type: (
            model.GetSymbolInfo(node).Symbol as INamedTypeSymbol
          )?.ToDisplayString()
        )
      )
      .Where(value => value.Type is not null && aliases.ContainsKey(value.Type))
      .ToArray();
    if (aliasNames.Length > 0)
    {
      var used = aliasNames.Select(value => value.Type!).Distinct().ToArray();
      syntax = syntax.ReplaceNodes(
        aliasNames.Select(value => value.Node),
        (originalNode, rewritten) =>
          SyntaxFactory
            .IdentifierName(
              aliases[
                aliasNames.First(value => value.Node == originalNode).Type!
              ]
            )
            .WithTriviaFrom(rewritten)
      );
      var unit = (CompilationUnitSyntax)syntax;
      foreach (var type in used)
      {
        if (
          unit.Usings.Any(value =>
            value.Alias?.Name.Identifier.ValueText == aliases[type]
          )
        )
          continue;
        unit = unit.AddUsings(
          SyntaxFactory
            .UsingDirective(SyntaxFactory.ParseName("global::" + type))
            .WithAlias(SyntaxFactory.NameEquals(aliases[type]))
        );
      }
      document = document.WithSyntaxRoot(unit);
      syntax = (await document.GetSyntaxRootAsync())!;
      model = (await document.GetSemanticModelAsync())!;
    }
    var names = syntax
      .DescendantNodes()
      .Where(node =>
        node is QualifiedNameSyntax or MemberAccessExpressionSyntax
      )
      .Where(node =>
        !node.Ancestors().Any(parent => parent is UsingDirectiveSyntax)
      )
      .Where(node =>
        model.GetSymbolInfo(node).Symbol is INamedTypeSymbol
        || (
          node.Parent is AttributeSyntax
          && model.GetSymbolInfo(node).Symbol
            is IMethodSymbol { MethodKind: MethodKind.Constructor }
        )
      )
      .ToArray();
    if (names.Length == 0 && aliasNames.Length == 0)
      continue;
    syntax = syntax.ReplaceNodes(
      names,
      (_, rewritten) =>
        rewritten.WithAdditionalAnnotations(Simplifier.Annotation)
    );
    document = document.WithSyntaxRoot(syntax);
    document = await ImportAdder.AddImportsAsync(
      document,
      Simplifier.Annotation
    );
    document = await Simplifier.ReduceAsync(document, Simplifier.Annotation);
    document = await Formatter.FormatAsync(document);
    var changed = await document.GetTextAsync();
    document = document.WithText(changed);
    var updatedModel = await document.GetSemanticModelAsync();
    if (
      updatedModel!
        .GetDiagnostics()
        .Any(value => value.Severity == DiagnosticSeverity.Error)
    )
    {
      Console.WriteLine($"Retained conflicting names: {path}");
      continue;
    }
    if (changed.ContentEquals(original))
      continue;
    solution = document.Project.Solution;
    pending.Add((path, changed.ToString()));
    Console.WriteLine(Path.GetRelativePath(rootDirectory, path));
  }
}
foreach (var project in solution.Projects)
{
  var compilation = await project.GetCompilationAsync();
  var errors = ErrorCounts(compilation);
  var introduced = errors
    .Where(value =>
      value.Value > baseline[project.Id].GetValueOrDefault(value.Key)
    )
    .ToArray();
  if (introduced.Length == 0)
    continue;
  foreach (var error in introduced)
    Console.Error.WriteLine(error.Key);
  throw new InvalidOperationException(
    "Simplification introduced compiler errors; no files have been written."
  );
}
foreach (var (path, text) in pending)
  await File.WriteAllTextAsync(path, text);
Console.WriteLine($"Simplified {pending.Count} files.");

static Dictionary<string, int> ErrorCounts(Compilation? compilation) =>
  (compilation?.GetDiagnostics() ?? [])
    .Where(value => value.Severity == DiagnosticSeverity.Error)
    .GroupBy(value => $"{value.Id}: {value.GetMessage()}")
    .ToDictionary(group => group.Key, group => group.Count());
